services:
  consul:
    image: hashicorp/consul
    extra_hosts: ['host.docker.internal:host-gateway']
    command: agent -server -bootstrap-expect=1 -client=0.0.0.0 -ui
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
  zipkin:
    image: openzipkin/zipkin
    extra_hosts: ['host.docker.internal:host-gateway']
    ports:
      - 9411:9411
